title: "Lior Batat"
description: "Welcome to my personal site!  
Here youâ€™ll find information about me and my research journey as an MSc student at WSOS.
"
theme: jekyll-theme-cayman
# add custume CSS
plugins: [jekyll-feed]
